### ISSUE TITLE
Can we have DNN7.x.x compatible version of the latest realese?

### ISSUE THREAD

**Issue by bhattjidotcom** [DNNCommunity/DNN.Feedback#16]
The latest version is not getting installed with DNN 7.x.x, may be because it is compiled with DNN 8 .dll file. 

However, I don't see any DNN8 specific features.

Can we have the current version compiled agaist DNN 7.x.x? so that it can be installed via ~/Install/Install.aspx?mode=InstallResources ?

Basically we need 6.4.4 version which can be installed via ~/Install/Install.aspx?mode=InstallResources

**Comment by EPTamminga** [comment]
The existing 6.4.3 version will work for DNN7?

**Comment by bhattjidotcom** [comment]
Hi EPT, the existing 6.4.3 version does work, however, for some reason, it does not get installed via ~/Install/Install.aspx?mode=InstallResources hence cannot be installed when the site is being installed the very first time (then ofcourse, you can install it via Host -> Extension)

**Comment by EPTamminga** [comment]
Any error messages being displayed? Any hints on what is wrong with the install zip?

**Comment by bhattjidotcom** [comment]
No error, it just doesn't get installed. The file remains in the ~/Install/ folder

**Comment by EPTamminga** [comment]
Does that happens with other (non standard) modules as well?

**Comment by bhattjidotcom** [comment]
NO, this happens only with this version of Feedback only. I guess, something is wrong in the manifest file

**Comment by EPTamminga** [comment]
I see that the EVS also hangs on checking the extension. 
I think I have found the problem. Line 3 in the .dnn6 manifest show a package version# of "**06.04.03.03**". This should be "**06.04.03**". 

In my test I  also renamed the manifest file from
 "DotNetNuke.Modules.Feedback.**dnn6**" to 
"DotNetNuke.Modules.Feedback.**dnn**"

If you rename/edit the manifest file and put it in the install zip. Can you try it again?. I have attached my modified install zip, so you can use that one as well.

[DotNetNuke.Modules.Feedback_06.04.03_Install.zip](https://github.com/DNNCommunity/DNN.Feedback/files/223397/DotNetNuke.Modules.Feedback_06.04.03_Install.zip)

**Comment by bhattjidotcom** [comment]
It now works !!! :+1: Thanks

**Comment by EPTamminga** [comment]
You are welcome.
