### ISSUE TITLE
feedback module error after update

### ISSUE THREAD

**Issue by josueexhume** [DNNCommunity/DNN.Feedback#17]
I recently updated the feedback module on my site, and its now currently giving these errors,
is there any fix for this?

`Error: Feedback is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object. at DotNetNuke.Modules.Feedback.Feedback.cmdSend_Click(Object sender, EventArgs e) --- End of inner exception stack trace ---`

**Comment by EPTamminga** [comment]
What version of the DNNFeedback module and DNN are you using? 
DNN7 and DNN8 require different versions.

**Comment by josueexhume** [comment]
i use version 6.5.1 of the feedback module, and i have DNN8

**Comment by EPTamminga** [comment]
The error mesage does not tell much. Can you export the feedback data in this case and attach it to this issue?

**Comment by josueexhume** [comment]
There was an error on my part. thank you!
