### ISSUE TITLE
The input data is not a complete block.

### ISSUE THREAD

**Issue by terfex** [DNNCommunity/DNN.Feedback#18]
After installing the latest version [06.05.01](https://github.com/DNNCommunity/DNN.Feedback/releases/tag/06.05.01), even on a fresh install, the following error appears when submitting the form. 
![capture](https://cloud.githubusercontent.com/assets/12871049/14937109/8e7680de-0f40-11e6-9d30-aa98d5c3cd78.PNG)
Any ideas what might be causing the error. I've tried adding in senders and recipient's addresses in manually within the settings but still no luck. I'm currently using DNN [08.00.02](https://dotnetnuke.codeplex.com/releases/view/620964).

I didn't have this issue previously on DNN 7 with earlier versions of the plugin. Not quite sure what changed.

**Comment by valadas** [comment]
I cannot reproduce this issue, it may be something with special characters or encoding. If you do find out some more details on how to be able to reproduce this issues, please reopen a new issue with steps to reproduce, such as language used, etc.
