### ISSUE TITLE
License should be License.txt

### ISSUE THREAD

**Issue by CPQcart** [DNNCommunity/DNN.Feedback#2]
I get the below error message
Message:Could not find file 'D:\WWWroot\CPQ\CPQcart.com\Install\Temp\wjsy1bah\License.txt'.
I can view it that temp dir & it is there but NO .txt
Also view here on codeplex shows it without .txt
Thanks in advance
Lee

**Comment by CPQcart** [comment]
Downloaded again, super user, install extension & error
Message:Could not find file 'D:\WWWroot\CPQ\CPQcart.com\Install\Temp\gfg0s33y\License.txt'.
At D:\WWWroot\CPQ\CPQcart.com\Install\Temp\gfg0s33y
only another dir "DNN.Feedback-master"
License.txt is at D:\WWWroot\CPQ\CPQcart.com\Install\Temp\gfg0s33y\DNN.Feedback-master\_buildfiles\MSBuild.CommunityTasks.License.txt

What can be the problem????
Thanks in advance for any help

**Comment by EPTamminga** [comment]
Please use an INSTALLATION release package, do not try to install a dump/zip of the project.

You can find the install packages in the release tab here on github, or in the download section of dnnfeedback.codeplex.com
