### ISSUE TITLE
Your feedback could not be sent to some or all of the intended recipients, please try again later: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by thabaum** [DNNCommunity/DNN.Feedback#21]
Your feedback could not be sent to some or all of the intended recipients, please try again later:
Object reference not set to an instance of an object.

Nothing showing up in error event logs.
Emails are sent to moderator.

When I did have it to send to both moderator and user and ran a test however I didn't get the email as the user submitting the form however the feedback is submitted and sent to the email configured in the module settings.

I do not have it setup to send to any roles just one email account.

Trying to figure out how to resolve this error. 

**Your feedback could not be sent to some or all of the intended recipients, please try again later:
Object reference not set to an instance of an object.**

**Comment by MayWorkman** [comment]
I too am seeing this error and nothing is sent to log files.

**Comment by sleupold** [comment]
this might be caused by wrong recipient address or SMTP server account.
Please always state the version of DNN and the module you are running on your site.

**Comment by valadas** [comment]
I cannot reproduce. Please submit a new issue with precise steps to reproduce the issue. It does look like an invalid address or smtp setting. I am closing this for now.
