### ISSUE TITLE
Category/Subject List admin page throws error when trying to edit / reorder items

### ISSUE THREAD

**Issue by eminentspoon** [DNNCommunity/DNN.Feedback#24]
An error of 'Input string was not in a correct format' is thrown when trying to edit or move up / down on the subject list admin page. This only occurs when the S.E.O. setting of 'Convert URLs to lowercase' is enabled in the host settings. The only way to reorder or edit an existing item through the front end admin pages is to disable this S.E.O. option.

**Comment by sytan79** [comment]
Where is the feedback list setting located as I couldn't find it in the latest version. How to customize the category/subject list? Please advice.

**Comment by eminentspoon** [comment]
@sytan79 You can find it under the 'Edit Category / Subject Lists' menu option under the Edit area of the feedback submission module (when logged in as a user with appropriate rights).

![Image of area where this can be changed](https://www.eminentspoon.com/attachments/github/dnnfeedback_issue21.png)

**Comment by dnndiva** [comment]
FYI...

On DNN 9.2.0 with Feedback 6.5.1, Feedback Module is causing huge issues. Pretty much is disabling inline editing, not letting the side admin bar load and making the page load and load forever. It is also stopping the site everytime a setting is changed on the feedback module. "Service Unavailable
HTTP Error 503. The service is unavailable."

After restarting the application pool, nothing to show on the admin logs other then a bunch of server updated, and Application Started. It wipes out what happened before.

By finding this thread, I changed the setting that set categories as a required field. Seems it has resolved the issues. But then nobody will be able to use categories. Not a problem for me as I am doing a demo, but I imagine lots of users out there would need this fixed.

**Comment by eminentspoon** [comment]
@dnndiva The latest couple of pull requests haven't been merged into the master branch so I don't know whether or not this module is actively monitored by an owner anymore! 

I have just downloaded a fresh 9.2.1 DNN platform install and installed the latest release of the Feedback module (06.05.01) onto it. I have been able to add the module to a fresh page, add some categories / subjects, change a few settings on the module itself and then submit. This all seemed to work OK on my end and submitted to my local SMTP server and committed to the database.

If you're able to get a set of instructions to replicate the issue that you're having, raise a fresh issue against this module and I'll have a look to see if I can see the underlying issue and (hopefully) sort it out!

**Comment by dnndiva** [comment]
Good to know. I still had some problems until I could go back in and delete all the categories, I also have a feeling it may have something to do with the values having space, but I don't have more time to play with it. Just deleting all the categories was good enough for my current purpose. Just letting people out there know the symptoms.

**Comment by EPTamminga** [comment]
I can easily merge the PR’s and create a new release, but I do not have the resources available to do a complete validation of a new release.
Will this help?

**Comment by EPTamminga** [comment]
As for a module owner: no there is no one specifically dedicated to this module. It is the foup of people that care about the core modules that try to catch up with any problem that arises.

**Comment by valadas** [comment]
What about @EPTamminga if you have time to merge and do a build but put the build result just in this issue and not as an official release, then if @dnndiva and @eminentspoon have time to give it a good test, we publish the release. Does that sound like a good idea. I too don't have enough time right not to do proper testing but if they can, then that would solve the problem.

**Comment by eminentspoon** [comment]
@valadas @EPTamminga I'm not sure of the cause of the issue that @dnndiva had as I was unable to replicate on a fresh environment so I can't comment on whether or not that is related to this issue but I would suspect not given the comments about version upgrade.

I raised this issue to address a problem I was having in our production environment which is what I raised #25 to resolve. The code for that pull request has been live on our production environment since June last year as it fixed our issue (was only a very minor bug fix amending a few regular expressions).

I don't really know what the best way forward with this issue / #25  is but I can state that the minor change has been tested on my end in the specific circumstances raised in the original issue! My aim was to make it available to anyone who had the same problem, the fix is obviously visible against my pull request so it is there if anyone needs it, just not as an official release.

**Comment by EPTamminga** [comment]
I was a little optimistic about the possibility to build a new version easily. Things like references, MSBuild tasks are not correct when I do a clone/build. I can correct that and make it work like that (clone/build/p[ackage), but it will take more time to get it in that state. If I go that way *references, build and packaging OK on clone), I will implement the DNNtc.MSBuild structure (similar to DNN.Reports and DNN.Events).

@valadas: What do you think we should do?

I also do not know if the module is DNN9.2 compliant, but that is the next step.

**Comment by valadas** [comment]
@EPTamminga I did test this module in Dnn 9.2 and it was working, well it was a short test, but it did not fail misarably at least. As for the build process, the modules I touched, I changed direct references with Nuget packages and created an MSBuild script if needed. I like the idea of the DNNtc.MSBuild, but I have not played with it much. Is there some documentation about it we could link to on the project readme.md text ?

**Comment by EPTamminga** [comment]
@valadas My build failed, I cloned the module as standalone project, not in a DNN install under desktopmodules, so all the references to DNN dll's were wrong. When I updated the NuGet packages the build companied about versions #'s being wrong. I could not find easily which version of DNN is the minimum to build against. I assume it is DNN8.0.0
It is my intention to have the modules to build without error directly after you clone the repository.
--> OK, so some work has to be done.
There was extensive documentation about DNNtc on CodePlex, but I saw that the GitHub repo is not complete. 
--> OK, some work has to be done.
If is good to read that the module worked on DNN9.2. 
--> OK, no urgent work to be done for this...

**Comment by valadas** [comment]
@EPTamminga , let me see if I can fix the references quickly...

**Comment by valadas** [comment]
@EPTamminga #32 should have fixed the build and references. Now even though this module has been tested working with 9.2, I suspect some areas may have issues, there are 13 places that use a deprecated api. Also, the install package is generated in the _packages folder if you are looking for it (it was like that).

**Comment by EPTamminga** [comment]
@valadas I will give it a go later this week (if time permits).
BTW: I already deleted most branches and only left the master branch. Makes life simpler.

**Comment by valadas** [comment]
Tested and merged, I may publish a new release later tonight or tomorrow.

**Comment by dnndiva** [comment]
FIY, I just tested Category value with spacing on version 06.06.00 and it still breaks the site. No issue when there's no spaces in the value. Have not tested other non-alphanumeric characters. If I do I am sure Tracy will eat my liver for breakfast, as he is having to restart the application every time the site gets Service Unavailable - HTTP Error 503. The service is unavailable.
