### ISSUE TITLE
Add and hide subjects

### ISSUE THREAD

**Issue by TheCakeGit** [DNNCommunity/DNN.Feedback#27]
Hi

Please check this screenshot:
https://imgur.com/a/6L1mm

In module settings how can I populate the subject dropdown. I then will make the field hidden and hopefully that subject will be sent out always (user won't see it).

Many thanks

**Comment by valadas** [comment]
@TheCakeGit You can populate the subject in the dropdown under the pencil when the module is in edit mode, you will see an item named "Edit Category/Subject Lists". When done, you can go back in the module settings and do what you describe here. I am closing this issue, feel free to reopen a new one if you encounter problems, trying to do this.
