### ISSUE TITLE
Commnets

### ISSUE THREAD

**Issue by abuhmead1987** [DNNCommunity/DNN.Feedback#3]
Dears, 
 I suggest to prevent admin from editing the message and it's subject, but in the other side let him add a comment and reply to the user who sent the feedback 

Kind Regards, 
Mohammad

**Comment by valadas** [comment]
This would change behaviour on existing users of the modules. Many people use this module as a testimonials module and need to edit the actual message and subject before making it publicly visible. Either to remove personal info or to correct spelling, etc. I am closing this as Wont Fix but if people disagree, please comment here so we can discuss it.
