### ISSUE TITLE
Submitting Feedback causes Page Load Exception

### ISSUE THREAD

**Issue by brentil** [DNNCommunity/DNN.Feedback#41]
## Describe the bug
Filling out a feedback form that includes email, name, subject, message, and captcha results in error when submitted.

## Software Versions
- DNN: 9.2.2
- Module: 6.6.0

## To Reproduce
1. Go to a page with Feedback module on it
2. Fill in your data
3. Click submit

## Expected behavior
Feedback sends.

## Screenshots
![image](https://user-images.githubusercontent.com/309174/46688229-cee8dd80-cbca-11e8-9457-8cf1a70d367d.png)

![image](https://user-images.githubusercontent.com/309174/46688147-9f39d580-cbca-11e8-8f02-f48030cb1eb0.png)

## Error log
**Note: Debug DLL's**
I put the Feedback 6.6.0 DotNetNuke.Modules.Feedback.pdb in the bin folder and reproduced the issue.

Error shown on submit page
> A critical error has occurred. Please check the Event Viewer for further details.Close
> AbsoluteURL:/Default.aspx
> DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
> ExceptionGUID:d4a5aaa5-3d45-400d-83b0-2d7ade77d915

Error in the logs

> AbsoluteURL:/Default.aspx
> DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
> ExceptionGUID:5b3a0c92-0124-4dcc-99ef-353a223553a8
> AssemblyVersion:9.2.2
> PortalId:2
> UserId:1
> TabId:103
> RawUrl:/ContactUs.aspx
> Referrer:http://WEBSITE/ContactUs.aspx
> UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
> ExceptionHash:NHBlaZudQLYFyseYYKxzyIH7QlY=
> Message:Specified argument was out of the range of valid values. Parameter name: index
> StackTrace:
> InnerMessage:Specified argument was out of the range of valid values. Parameter name: index
> InnerStackTrace:
> at System.Web.UI.ControlCollection.get_Item(Int32 index) at DotNetNuke.Modules.Feedback.Feedback.cmdSend_Click(Object sender, EventArgs e) at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e) at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument) at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
> Source:
> FileName:
> FileLineNumber:0
> FileColumnNumber:0
> Method:

**Comment by valadas** [comment]
I can reproduce on some sites, will try to fix that today and publish a new release...

**Comment by brentil** [comment]
I just installed it on our development server and feedback is flowing again!  Thank you.

**Comment by valadas** [comment]
You are welcome
