### ISSUE TITLE
Wrong code in .aspx files causes validation to be not tranlsated

### ISSUE THREAD

**Issue by eclipse79** [DNNCommunity/DNN.Feedback#5]
Hello, 
this line in feedback.aspx: 
<asp:requiredfieldvalidator id="valEmailConfirm" runat="server" cssclass="dnnFormMessage dnnFormError" Display="Dynamic" errormessage="Emails are different." 
   				        controltovalidate="txtEmailConfirm" InitialValue="" Enabled="false" resourcekey="valEnmailConfirm.Error"></asp:requiredfieldvalidator>

contains "valEnmailConfirm.Error" that should be "valEmailConfirm.Error". 

Please correct it.
Thanks
Fabio

**Comment by EPTamminga** [comment]
Can you supply a pull request?

Met vriendelijke groet,
Ernst Peter Tamminga

Op 17 nov. 2015 om 14:03 heeft eclipse79 <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hello,
this line in feedback.aspx:
controltovalidate="txtEmailConfirm" InitialValue="" Enabled="false" resourcekey="valEnmailConfirm.Error">/asp:requiredfieldvalidator

contains "valEnmailConfirm.Error" that should be "valEmailConfirm.Error".

Please correct it.
Thanks
Fabio

—
Reply to this email directly or view it on GitHub<https://github.com/DNNCommunity/DNN.Feedback/issues/5>.




CEO
[XCESS expertise center b.v.]<https://www.xcess.nl/>    XCESS expertise center b.v.
Storkstraat 19
3833 LB Leusden, NL
I www.xcess.nl<https://www.xcess.nl>    M
D
T
E

+31-6-21564750
+31-33-4335101
+31-33-4335151
ernst.peter.tamminga@xcess.nl




________________________________

Dit e-mail bericht is alleen bestemd voor de geadresseerde, verstrekking aan en gebruik door anderen is niet toegestaan. Indien u niet de geadresseerde bent, wordt u vriendelijk verzocht de verzender hiervan op de hoogte te stellen en het bericht te verwijderen. In verband met de elektronische verzending kunnen aan de inhoud van dit bericht geen rechten worden ontleend. Tenzij schriftelijk anders is overeengekomen, zijn op al onze rechtsbetrekkingen de XCESS leveringsvoorwaarden<https://www.xcess.nl/Portals/0/Downloads/%5bXCESS%5d%20Algemene%20Leveringsvoorwaarden08052008NL.pdf> van toepassing. Deze zijn gedeponeerd bij de Kamer van Koophandel Amersfoort onder nummer 31047117 en bij de griffie van de arrondissementsrechtbank te Amsterdam onder nummer 36/2003 en worden op verzoek toegezonden. Toepasselijkheid van eventuele inkoop- of andere voorwaarden van opdrachtgever dan wel van derden wordt dan ook uitdrukkelijk van de hand gewezen door XCESS.

**Comment by EPTamminga** [comment]
Is solved in the new version 6.5.0
