### ISSUE TITLE
Messages Localization

### ISSUE THREAD

**Issue by lazito** [DNNCommunity/DNN.Feedback#50]
Hello,
Where do I translate the messages sent by the module?
Attachment message in Outlook
[Estilo de memorando.pdf](https://github.com/DNNCommunity/DNN.Feedback/files/3370676/Estilo.de.memorando.pdf)

**Comment by valadas** [comment]
That would be 2 parts. The message in your pdf is a Dnn notification message. The module specific part would be translated in the module resource files.

In Site Settings -> Languages -> Symbols character icon or the language to edit

Then in the dropdown you will navigate to Local Resources -> DesktopModules -> Feedback -> App_LocalResources and edit those files then save.

Now for the header of that message, this is part of the core language pack. If available for your language, you can install it from Extensions -> Available Extensions, select "Core Language Packs" from the dropdown and install the one for your language.

If that did not get translated, then we need to find each key that is missing translation. I _think_ you will find most for this area in DesktopModules/CoreMessaging/App_LocalResources
