### ISSUE TITLE
Message limited to 10 characters after upgrade to DNN 9.4.1

### ISSUE THREAD

**Issue by WHairstonLOI** [DNNCommunity/DNN.Feedback#51]
## Describe the bug
After upgrading our site from DNN 9.1.1 to DNN 9.4.1, the message body text control is limited to only 10 characters. Looking at the HTML of the page, the generated textarea element has a maxlength=10 attribute, although the size of the message field is set to contain up to 1000 characters in the module settings.

## Software Versions
- DNN: 09.04.01
- Module: 06.06.02

## To Reproduce
1. Go to our site at https://www.logicaloperators.com/Contact-Us
2. Click on Message Body in Feedback form
3. Start typing. You can only enter 10 characters.
4. See error: examine HTML of page

## Expected behavior
Expect to be able to enter the number of characters configured.

## Screenshots
N/A

## Error log
**Note: Debug DLL's**
Please replace the current extension DLL's with the debug DLL's (if these are available with the release) and reproduce the error with the debug DLL's before pasting the error log.
N/A

Paste the error log that is related to this issue.
N/A

## Additional context
N/A

**Comment by valadas** [comment]
Wow, I am surprised this was not spotted earlier, I do see that maxLenght in the ascx. Odd.

Well there is a documented workaround to edit that file, but certainly something to fix on next release.

**Comment by WHairstonLOI** [comment]
I didn’t really have a chance to look deeper last night, but as previously noted, I have that same version of the module running as expected on other client sites that are based on DNN 9.3.2 or lower and they all run WITHOUT generating the maxlength attribute in the resulting HTML (although the maxlength attribute is present in their Feedback.ascx files). Does the attribute get adjusted somewhere in code before the HTML is generated?

**Comment by valadas** [comment]
Yes, there is a setting for it. I only have a french instance right now to look at so the labels I mention here might be a bit off, but under:

Module Settings -> Form and Fields Settings -> Message maximum lenght

And I believe this overrides the maxLenght of that field. Now I still think 10 for a default is kinda short, we should at least make the default 250 or some such, 10 is ridiculous for any message.

**Comment by thebowenmango** [comment]
Hi Team,
I found it was the first row that had the 10 character limit. If you hit enter, you lose the 10 character limit on the subsequent lines.

**Comment by ChrisHammond** [comment]
I found that my site is experiencing this as well.

![image](https://user-images.githubusercontent.com/1654166/68078846-d0281200-fdac-11e9-9283-f9ab8fcf6569.png)


Even though the setting is 1000 characters, always limited to 10. Doesn't matter if you hit enter or not in the text field, still limited.

**Comment by njhvidberg** [comment]
Hi
Just installed ver. 6.6.2 and it still has the error. Any new version on its way?
I can add that the number of characters remaining is acting on the specified Max Message Length settings.

**Comment by sleupold** [comment]
there is an open PR to fix it.

**Comment by valadas** [comment]
Resolved in 6.6.3 which I will publish in a minute...
