### ISSUE TITLE
CAPTCHA doesn't work.

### ISSUE THREAD

**Issue by JaySMa** [DNNCommunity/DNN.Feedback#53]
## Describe the bug
Feedback form has CAPTCHA, but it's not display.  Only the "Refresh Captcha" link is being shown.

## Software Versions
- DNN: Evoq 9.3.7.1-1
- Module: 06.06.02

## To Reproduce
Visit any page which has the feedback form and CAPTCHA enabled.

## Expected behavior
CAPTCHA should display.

## Screenshots
![CAPTCHA](https://user-images.githubusercontent.com/11575998/69658493-4afde900-104a-11ea-8474-5de4bd9addf4.PNG)

## Error log
Didn't see anything in the event logs.

## Additional context
Trying to paste the HTML code; probably won't work.  Makes call to "Telerik.Web.UI.WebResource.axd"

`<img id="dnn_ctr13790_Feedback_ctlCaptcha_CaptchaImageUP" alt="" src="/Telerik.Web.UI.WebResource.axd?type=rca&amp;isc=true&amp;guid=1e5fa36d-5783-4a50-af11-e74b080b30f0" style="height:50px;width:180px;display:block;">`

**Comment by valadas** [comment]
@JaySMa Can you reproduce this issue in Platform ?
The last time I checked it was working and the module also has options now for recaptcha support...

**Comment by JaySMa** [comment]
Sorry, we're getting back to our Evoq 9 update and remember we had this issue.

Checked a feedback module which was having issues and configured the Captcha for "Anonymous Users Only" and it doesn't show.  Configured for "All Users" and it doesn't show either.

What do you mean by reproduct in Platform?

Thank you..

**Comment by valadas** [comment]
> What do you mean by reproduct in Platform? 

I mean is this Evoq specific? Do you have the same issue on Dnn Platform ? Evoq not being open source, if it is Evoq specifc, it would have to be handled on their side... I have this working fine on multiple Dnn Platform instances, so trying to find what could cause it for you...

**Comment by valadas** [comment]
Oh, reading this again, yeah, it is very probably an Evoq specifc issue, that DnnCaptcha control depends on Telerik and I believe that library is not present in Evoq. Now it will also be removed from Dnn Platform soon, so, I would recommend using the google recaptcha option for now. On the next update of this module, unless there is a new captcha control in Dnn Platform, this option will have to be removed anyway... Just to clarify the recaptcha option should stay but the standard DnnCaptcha should be taken out.

**Comment by JaySMa** [comment]
No problem.  For the time being, I just removed that CAPTCHA option and added the tracking by IP so multiple posts shouldn't occur.

Thank you..

**Comment by valadas** [comment]
Support for ReCaptcha/NoCaptcha was also added in 7.0.0 if you want something nicer...
