### ISSUE TITLE
No captcha characters showing.

### ISSUE THREAD

**Issue by EdwardGraham** [DNNCommunity/DNN.Feedback#55]
Using DNN 9.6.1 and module Feedback 6.6.2 and Microsoft Edge as a browser.
On the feedback for settings I have captcha enabled, with medium selected for both settings.
The problem is the actual captcha generated letters are not displayed on the screen. Instead you get a broken graphic icon. This worked in DNN 9.4 I believe. No backup to try. Anyone else got the problem? Thank you, DaleGraham

**Comment by valadas** [comment]
I did not test but it may be a couple of things:
- Telerik registration changes in 9.6.0
- jQuery changes in 9.6.0

That being said, the built-in captcha is not great, have you considered using the reCaptcha option? All you need is to get a google API key and change the type of captcha in the module settings.

**Comment by valadas** [comment]
No, actually, the captcha control does work in Dnn 9.6.1 itself, so I guess my 2 previous assumptions are probably wrong.

Do you have any errors in the browser console (F12 in most browsers) or in the Admin Logs or in the Portals/_default/logs folder that might bring some clues here...

**Comment by valadas** [comment]
I can reproduce the issue though, we will need to look at how it is done in Platform vs here, but here it looks related to the Telerik registration changes. I won't have time to look into this for a couple of weeks, as a workaround for now, I would suggest using Google noCaptcha option.

**Comment by EdwardGraham** [comment]
I appreciate your help and glad you were able to reproduce the problem.  As for using google recaptcha, I am lost.  Been reading lots on google but haven't figured anything out yet. I would appreciate any links you can supply.  Thank you, Edward Graham

**Comment by valadas** [comment]
You would go to https://www.google.com/recaptcha/intro/v3.html login if you have a google account or create an account. Then click the add button.

Give it a name, choose reCAPTCHA version 2, then choose the invisible reCAPTCHA option.
Add the domain names you want this API key to work on and save. You will receive a site key and a secret key, copy that somewhere.

Then in the Feedback module:
- Go to the module settings
- Under Submission and Security Settings, check the "Use Google NoCaptcha" checkbox.
- Paste your site key and your private key
- Save the settings.

**Comment by EdwardGraham** [comment]
Thanks that worked great.  Another issue is subject box only allows 10 characters even if you have 1000 or even 10000 allowed in settings.  Thank you.

**Comment by valadas** [comment]
Yes, there is a PR for it already, I just lack time to produce a new release, it is on my very long todo list. If you want a quick fix for that you could modify manually the view as in here https://github.com/DNNCommunity/DNN.Feedback/pull/52/files

**Comment by EdwardGraham** [comment]
Hey thanks!  That was the EASY BUTTON!

**Comment by valadas** [comment]
You are welcome, I will leave the issue open though, we need to fix this somehow.

**Comment by brewadmin** [comment]
Adding Google recaptcha to 90 websites

**Comment by WHairstonLOI** [comment]
Just wanted to bump this issue as I also encountered the same problem today upgrading the Feedback module from 6.6.2 to 6.6.3 on a site before upgrading from DNN 9.5.0 to 9.7.2.

@valadas Appreciate the step-by-step walkthrough for setting up Google reCAPTCHA as an alternate solution/workaround.
