### ISSUE TITLE
Module Set up

### ISSUE THREAD

**Issue by LuisGMMarques** [DNNCommunity/DNN.Feedback#68]
Hello

I'm trying to set up a feedback form but when I put the module on a page I only get settings for a "show users feedback on page" type of section. How can I set up the form? 

thank you

**Comment by WillStrohl** [comment]
What version of DNN are you using?  Are you using Evoq too, or the open-source DNN Platform?  Also, what version of the module are you seeing this occur in?  If there are any errors that happen to be related, please provide those as well.  

[Video: How to View/Use the Admin Logs and Log4Net](https://www.youtube.com/watch?v=uyNebzEy8Bk&list=PLojRGd54eWTiK-0y8o5EBYVcCY2yzhTZk)

**Comment by LuisGMMarques** [comment]
I'm using Open-Source DNN in the version v. 09.06.02
Feedback Module version 6.7.0

No Error on admin log

**Comment by LuisGMMarques** [comment]
Ok, I'm dumb. Whenever I put the module in I never noticed the form module was getting placed some panes below. 

I came across another issue, I'm trying to leave the zip code validation blank but after saving it goes back to the default validation formula

**Comment by WillStrohl** [comment]
> Ok, I'm dumb. Whenever I put the module in I never noticed the form module was getting placed some panes below.
> 
> I came across another issue, I'm trying to leave the zip code validation blank but after saving it goes back to the default validation formula

I think it sounds like you found a solution the issue you reported.  

I'd recommend creating a new issue for the next challenge you're mentioning.  :)
