### ISSUE TITLE
Urgently needed an update to suit DNN 8.0.0.446

### ISSUE THREAD

**Issue by bhattjidotcom** [DNNCommunity/DNN.Feedback#9]
Urgently needed an update to suit DNN 8.0.0.446

The module broke.

Also, please note, the current version doesn't support Install via /Install/Install.aspx?mode=InstallResources

**Comment by cpaterra** [comment]
This module is broken in version 8 due to the breaking changes around Telerik. If the module has it's references updated and recompiles the issues should be resolved. 

The errors are shown on this issue logged in the platform project tracker (adding comment here so it can be fixed): https://dnntracker.atlassian.net/browse/DNN-8222.

**Comment by EPTamminga** [comment]
@bhattjidotcom: I have a beta for you with the changes that Oliver Hine created and build against DNN8. Consider this BETA, I did not test it extensively. Please make a back-up of your site before installing. If things work correclt, please give some feedback, so I can make a formal release.
[DotNetNuke.Modules.Feedback_06.05.00_Install.zip](https://github.com/DNNCommunity/DNN.Feedback/files/80041/DotNetNuke.Modules.Feedback_06.05.00_Install.zip)

**Comment by bhattjidotcom** [comment]
Installed properly, and also gives me message that "Email Sent" but I have not received the email in my account (specified in the "Send To")

Also the other "Feedback Comments" control is blank :( don't know why :(

I will test, by installing "~//Install/Install.aspx?mode=InstallResources" later

**Comment by EPTamminga** [comment]
Emails work the same as in the previous version. I have created a new install with some enhancements. Please give this one a try?
[DotNetNuke.Modules.Feedback_06.05.01_Install.zip](https://github.com/DNNCommunity/DNN.Feedback/files/81398/DotNetNuke.Modules.Feedback_06.05.01_Install.zip)

**Comment by bhattjidotcom** [comment]
Installed via  "~//Install/Install.aspx?mode=InstallResources" succesfully.

Seems to be working fine

**Comment by EPTamminga** [comment]
Update release published
